# Generated by Django 5.2.5 on 2025-09-25 23:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('pseudonimo', models.CharField(blank=True, max_length=50)),
                ('biografia', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_comuna', models.CharField(max_length=5)),
                ('nombre_comuna', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='', max_length=50)),
                ('numero', models.CharField(default='', max_length=10)),
                ('departamento', models.CharField(blank=True, max_length=10)),
                ('detalles', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_biblioteca', models.CharField(max_length=100)),
                ('web', models.CharField(blank=True, max_length=255)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_direccion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_lector', models.IntegerField(unique=True)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre_lector', models.CharField(max_length=255)),
                ('correo_lector', models.CharField(blank=True, max_length=255)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
                ('id_direccion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('paginas', models.IntegerField()),
                ('copias', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fisico', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
                ('id_categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.nacionalidad'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True)),
                ('fecha_retorno', models.DateTimeField(blank=True)),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_tipo_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tipocategoria'),
        ),
    ]
