# Generated by Django 5.2.5 on 2025-09-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_tipoparametro_parametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None),
        ),
    ]
