# Generated by Django 5.2.6 on 2025-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_lector_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
