# Generated by Django 5.2.6 on 2025-10-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_autor_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='nacionalidad',
        ),
    ]
