# Generated by Django 5.2.6 on 2025-10-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_remove_autor_nacionalidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='id_nacionalidad',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='biblioteca',
            old_name='id_direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='id_tipo_categoria',
            new_name='tipo_categoria',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='id_comuna',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='lector',
            old_name='id_biblioteca',
            new_name='biblioteca',
        ),
        migrations.RenameField(
            model_name='lector',
            old_name='id_direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='id_biblioteca',
            new_name='biblioteca',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='parametro',
            old_name='id_tipo_parametro',
            new_name='tipo_parametro',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_lector',
            new_name='lector',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_libro',
            new_name='libro',
        ),
    ]
