# Generated by Django 4.2.7 on 2025-11-03 19:52

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_remove_lector_digito_verificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None, validators=[biblioteca.models.validar_mayoria_edad]),
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.CharField(max_length=12, unique=True, validators=[biblioteca.models.validar_rut]),
        ),
    ]
