# Generated by Django 4.2.7 on 2025-11-04 19:12

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_autor_genero_alter_lector_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato1', models.CharField(max_length=10, validators=[biblioteca.models.validar_datos])),
            ],
        ),
    ]
